name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: 428866/deusbarbershop:latest
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
