name: Docker CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Integration Tests
    runs-on: ubuntu-latest
    env:
        DefaultConnection: ${{secrets.CONNECTION_STRING}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.x.x'
      - run: dotnet test

  build:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: 428866/deus:latest
      -
     
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
